### ISSUE TITLE
[BUG] `RowConversionTest` fails after UNKNOWN_NULL_COUNT changes

### ISSUE THREAD

**Issue by mythrocks** [NVIDIA/spark-rapids-jni#1169]
Repro:
```bash
build/build-in-docker  package -DCPP_PARALLEL_LEVEL=30  -DBUILD_TESTS=ON -Dtest=RowConversionTest -DCMAKE_CUDA_ARCHITECTURES=NATIVE
```

Error:
```
org.opentest4j.AssertionFailedError: Null Count For Column 0 ==> expected: <1> but was: <0>        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:166)        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:660)
        at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:114)        at ai.rapids.cudf.AssertUtils.assertPartialColumnsAreEqual(AssertUtils.java:95)
        at ai.rapids.cudf.AssertUtils.assertPartialTablesAreEqual(AssertUtils.java:250)
        at ai.rapids.cudf.AssertUtils.assertTablesAreEqual(AssertUtils.java:260)        at com.nvidia.spark.rapids.jni.RowConversionTest.fixedWidthRowsRoundTrip(RowConversionTest.java:86)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
        at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by mythrocks** [comment]
Looks like this isn't related to the changes in #1148 or #1155. This test is failing after merging [cudf/pull/13372](https://github.com/rapidsai/cudf/pull/13372). 

On round-tripping a test vector, the null mask is coming out empty. This then sets the null-count to null.

**Comment by mythrocks** [comment]
I'm working on a fix now. Will post a PR shortly.
