### ISSUE TITLE
[BUG] Build process fail on cuda12 arm environment

### ISSUE THREAD

**Issue by wjxiz1992** [NVIDIA/spark-rapids-jni#2141]
**Describe the bug**
Several unit tests fail, most of them are throwing the same error message 

```
[2024-06-13T10:09:34.583Z] 	Caused by: java.util.concurrent.ExecutionException: ai.rapids.cudf.CudfException: RMM failure at: /home/jenkins/agent/workspace/spark-rapids-jni_nightly-dev/target/libcudf/cmake-build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:138: Error, Initial pool size required to be a multiple of 256 bytes
[2024-06-13T10:09:34.584Z] 		at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[2024-06-13T10:09:34.584Z] 		at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[2024-06-13T10:09:34.584Z] 		at ai.rapids.cudf.PinnedMemoryPool.getSingleton(PinnedMemoryPool.java:90)
[2024-06-13T10:09:34.584Z] 		... 73 more
[2024-06-13T10:09:34.584Z] 	Caused by: ai.rapids.cudf.CudfException: RMM failure at: /home/jenkins/agent/workspace/spark-rapids-jni_nightly-dev/target/libcudf/cmake-build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:138: Error, Initial pool size required to be a multiple of 256 bytes
[2024-06-13T10:09:34.584Z] 		at ai.rapids.cudf.Rmm.setCudfPinnedPoolMemoryResource(Native Method)
[2024-06-13T10:09:34.584Z] 		at ai.rapids.cudf.PinnedMemoryPool.<init>(PinnedMemoryPool.java:227)
[2024-06-13T10:09:34.584Z] 		at ai.rapids.cudf.PinnedMemoryPool.lambda$initialize$1(PinnedMemoryPool.java:142)
[2024-06-13T10:09:34.584Z] 		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2024-06-13T10:09:34.584Z] 		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2024-06-13T10:09:34.584Z] 		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2024-06-13T10:09:34.584Z] 		at java.lang.Thread.run(Thread.java:750)
[2024-06-13T10:09:34.584Z] Caused by: java.util.concurrent.ExecutionException: ai.rapids.cudf.CudfException: RMM failure at: /home/jenkins/agent/workspace/spark-rapids-jni_nightly-dev/target/libcudf/cmake-build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:138: Error, Initial pool size required to be a multiple of 256 bytes
[2024-06-13T10:09:34.584Z] 	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[2024-06-13T10:09:34.584Z] 	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
[2024-06-13T10:09:34.584Z] 	at ai.rapids.cudf.PinnedMemoryPool.getSingleton(PinnedMemoryPool.java:90)
[2024-06-13T10:09:34.584Z] 	... 69 more
[2024-06-13T10:09:34.584Z] Caused by: [CIRCULAR REFERENCE: ai.rapids.cudf.CudfException: RMM failure at: /home/jenkins/agent/workspace/spark-rapids-jni_nightly-dev/target/libcudf/cmake-build/_deps/rmm-src/include/rmm/mr/device/pool_memory_resource.hpp:138: Error, Initial pool size required to be a multiple of 256 bytes]
```

**Steps/Code to reproduce bug**
```
mvn -Dmaven.wagon.http.retryHandler.count=3 -B clean package -s ci/settings.xml -P mirror-apache-to-urm -Psource-javadoc,arm64 -DCPP_PARALLEL_LEVEL=80 -Dlibcudf.build.configure=true -DUSE_GDS=OFF '-Dtest=*,!CuFileTest,!CudaFatalTest,!ColumnViewNonEmptyNullsTest' -DBUILD_TESTS=ON -DBUILD_FAULTINJ=OFF -Dcuda.version=cuda12 -DUSE_SANITIZER=ON
```
**Expected behavior**
Build pass

**Environment details (please complete the following information)**
 - cuda12
 - arm
 - Submodule path 'thirdparty/cudf': checked out 'f7ba6ab47ac994e6a1363119c01eee5dd6304181'
```
[2024-06-13T09:31:02.806Z] +---------------------------------------------------------------------------------------+
[2024-06-13T09:31:02.806Z] | NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
[2024-06-13T09:31:02.806Z] |-----------------------------------------+----------------------+----------------------+
[2024-06-13T09:31:02.806Z] | GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
[2024-06-13T09:31:02.806Z] | Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
[2024-06-13T09:31:02.806Z] |                                         |                      |               MIG M. |
[2024-06-13T09:31:02.806Z] |=========================================+======================+======================|
[2024-06-13T09:31:02.806Z] |   0  Tesla T4                       Off | 00000000:01:00.0 Off |                    0 |
[2024-06-13T09:31:02.806Z] | N/A   40C    P8              15W /  70W |      2MiB / 15360MiB |      0%      Default |
[2024-06-13T09:31:02.806Z] |                                         |                      |                  N/A |
[2024-06-13T09:31:02.806Z] +-----------------------------------------+----------------------+----------------------+
[2024-06-13T09:31:02.806Z]                                                                                          
[2024-06-13T09:31:02.806Z] +---------------------------------------------------------------------------------------+
[2024-06-13T09:31:02.806Z] | Processes:                                                                            |
[2024-06-13T09:31:02.806Z] |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
[2024-06-13T09:31:02.806Z] |        ID   ID                                                             Usage      |
[2024-06-13T09:31:02.806Z] |=======================================================================================|
[2024-06-13T09:31:02.806Z] |  No running processes found                                                           |
```

**Comment by bdice** [comment]
This error should be resolved by https://github.com/rapidsai/cudf/pull/16024.

**Comment by wjxiz1992** [comment]
close this, I've confirmed the fix above works.
