### ISSUE TITLE
[BUG] testBasicBUFNCpu failed

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#2668]
Recent nightly build had a test failure in testBasicBUFNCpu:
```
[2024-12-09T13:21:51.992Z] [ERROR] testBasicBUFNCpu  Time elapsed: 2.036 s  <<< ERROR!
[2024-12-09T13:21:51.992Z] java.util.concurrent.TimeoutException: TEST THREAD ONE WAITING FOR STATE THREAD_BUFN BUT STATE IS THREAD_RUNNING
[2024-12-09T13:21:51.992Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest$TaskThread.pollForState(RmmSparkTest.java:123)
[2024-12-09T13:21:51.992Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest.testBasicBUFNCpu(RmmSparkTest.java:1071)
[2024-12-09T13:21:51.992Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[...]
```

<details>
<summary>Full stack details</summary>

```
[2024-12-09T13:21:51.992Z] [ERROR] testBasicBUFNCpu  Time elapsed: 2.036 s  <<< ERROR!
[2024-12-09T13:21:51.992Z] java.util.concurrent.TimeoutException: TEST THREAD ONE WAITING FOR STATE THREAD_BUFN BUT STATE IS THREAD_RUNNING
[2024-12-09T13:21:51.992Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest$TaskThread.pollForState(RmmSparkTest.java:123)
[2024-12-09T13:21:51.992Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest.testBasicBUFNCpu(RmmSparkTest.java:1071)
[2024-12-09T13:21:51.992Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-12-09T13:21:51.992Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-12-09T13:21:51.992Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-12-09T13:21:51.992Z] 	at java.lang.reflect.Method.invoke(Method.java:498)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
[2024-12-09T13:21:51.992Z] 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-12-09T13:21:51.992Z] 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-12-09T13:21:51.992Z] 	at java.util.ArrayList.forEach(ArrayList.java:1259)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:155)
[2024-12-09T13:21:51.992Z] 	at org.junit.platform.surefire.provider.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:134)
[2024-12-09T13:21:51.992Z] 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:383)
[2024-12-09T13:21:51.992Z] 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:344)
[2024-12-09T13:21:51.992Z] 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
[2024-12-09T13:21:51.992Z] 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:417)
```
</details>

**Comment by pxLi** [comment]
a repro at spark-rapids-jni_nightly-dev, run: 1037

**Comment by pxLi** [comment]
a repro at spark-rapids-jni_submodule-sync-pre_release, run:1152

```
[2025-05-21T05:22:42.241Z] [ERROR] testBasicBUFNCpu  Time elapsed: 2.027 s  <<< ERROR!

[2025-05-21T05:22:42.241Z] java.util.concurrent.TimeoutException: TEST THREAD ONE WAITING FOR STATE THREAD_BUFN_WAIT BUT STATE IS THREAD_BLOCKED

[2025-05-21T05:22:42.241Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest$TaskThread.pollForState(RmmSparkTest.java:123)

[2025-05-21T05:22:42.241Z] 	at com.nvidia.spark.rapids.jni.RmmSparkTest.testBasicBUFNCpu(RmmSparkTest.java:1061)

[2025-05-21T05:22:42.241Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2025-05-21T05:22:42.241Z] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2025-05-21T05:22:42.241Z] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2025-05-21T05:22:42.241Z] 	at java.lang.reflect.Method.invoke(Method.java:498)

[2025-05-21T05:22:42.241Z] 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)

[2025-05-21T05:22:42.241Z] 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
```

**Comment by pxLi** [comment]
another repro at spark-rapids-jni_nightly-dev/1163 cuda12-arm64 build
